const ConfigPartition = {
	AccessAutoConsentIfUserProcessNotRunning: 'AppConfig-SystemSettings',
	AutoConsentIfUserProcessNotRunning: 'AppConfig-SystemSettings',
	AutoConsentToBackstage: 'AppConfig-SystemSettings',
	ClientServiceTimeoutMilliseconds: 'AppConfig-SystemSettings',
	EmptySessionProgramsToStart: 'AppConfig-SystemSettings',
	IsBackstageDefault: 'AppConfig-SystemSettings', // 19.3+
	IsUserAllowedToRequireConsent: 'AppConfig-SystemSettings',
	MaxRetrySleepMilliseconds: 'AppConfig-SystemSettings',
	SupportAutoConsentIfUserProcessNotRunning: 'AppConfig-SystemSettings',

	AccessHideWallpaperOnConnect: 'AppConfig-UserInterfaceSettings',
	AccessLockMachineOnConnect: 'AppConfig-UserInterfaceSettings',
	AccessLockMachineOnDisconnect: 'AppConfig-UserInterfaceSettings',
	AccessShowBalloonOnConnect: 'AppConfig-UserInterfaceSettings',
	AccessShowBalloonOnHide: 'AppConfig-UserInterfaceSettings',
	AccessShowSystemTrayIcon: 'AppConfig-UserInterfaceSettings',
	AccessShowUnderControlBanner: 'AppConfig-UserInterfaceSettings',
	AccessSuspendControlAtStartup: 'AppConfig-UserInterfaceSettings',
	AlwaysDeleteSessionOnExit: 'AppConfig-UserInterfaceSettings',
	AlwaysOnTop: 'AppConfig-UserInterfaceSettings',
	AllowGuestInitiatedFileTransfer: 'AppConfig-UserInterfaceSettings',
	AutoConsentAfterSeconds: 'AppConfig-UserInterfaceSettings',
	BeepOnConnect: 'AppConfig-UserInterfaceSettings',
	CaptureControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	CapturesDirectory: 'AppConfig-UserInterfaceSettings',
	ColorTheme: 'AppConfig-UserInterfaceSettings', // 19.0+
	ControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	DisableClipboardCapture: 'AppConfig-UserInterfaceSettings',
	DisabledCommandNames: 'AppConfig-UserInterfaceSettings',
	FullScreenWhenMaximized: 'AppConfig-UserInterfaceSettings',
	FilesDirectory: 'AppConfig-UserInterfaceSettings',
	GuestAlwaysOnTop: 'AppConfig-UserInterfaceSettings',
	HelpProviderName: 'AppConfig-UserInterfaceSettings',
	HideWallpaperOnConnect: 'AppConfig-UserInterfaceSettings',
	HostAlwaysOnTop: 'AppConfig-UserInterfaceSettings',
	IsMicrophoneMuted: 'AppConfig-UserInterfaceSettings',
	MeetingControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	MeetingDockControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	MeetingSuspendControlAtStartup: 'AppConfig-UserInterfaceSettings',
	ShowBalloonOnConnect: 'AppConfig-UserInterfaceSettings',
	ShowFeedbackSurveyForm: 'AppConfig-UserInterfaceSettings',
	ShowCloseDialogOnExit: 'AppConfig-UserInterfaceSettings',
	ShowSystemTrayIcon: 'AppConfig-UserInterfaceSettings',
	ShowTrayIconContextMenuStoreLoginCredentialsItem: 'AppConfig-UserInterfaceSettings', // 20.5+
	SupportAccessDockControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	SupportAccessGuestControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	SupportAccessGuestRenderControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	SupportAccessGuestRenderDockControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	SupportAccessHostControlPanelIDs: 'AppConfig-UserInterfaceSettings',
	SupportAccessHostFullScreenWhenMaximized: 'AppConfig-UserInterfaceSettings',
	SupportHideWallpaperOnConnect: 'AppConfig-UserInterfaceSettings',
	SupportLockMachineOnConnect: 'AppConfig-UserInterfaceSettings',
	SupportLockMachineOnDisconnect: 'AppConfig-UserInterfaceSettings',
	SupportShowBalloonOnConnect: 'AppConfig-UserInterfaceSettings',
	SupportShowBalloonOnHide: 'AppConfig-UserInterfaceSettings',
	SupportShowSystemTrayIcon: 'AppConfig-UserInterfaceSettings',
	SupportShowUnderControlBanner: 'AppConfig-UserInterfaceSettings',
	SupportSuspendControlAtStartup: 'AppConfig-UserInterfaceSettings',
	ToolboxDirectory: 'AppConfig-UserInterfaceSettings',

	BlockIPs: 'WebConfig-PageSettings',
	MaxLongestTicketReissueIntervalSeconds: 'WebConfig-PageSettings',
	MinAuthenticationFactorCount: 'WebConfig-PageSettings',
	RestrictToIPs: 'WebConfig-PageSettings',

	AccessSessionExpireSeconds: 'WebConfig-OtherSettings',
	AccessTokenExpireSeconds: 'WebConfig-OtherSettings',
	AcknowledgeMessageDelaySeconds: 'WebConfig-OtherSettings',
	AllowPasswordAutoComplete: 'WebConfig-OtherSettings',
	ApplicationPingTimeSeconds: 'WebConfig-OtherSettings',
	AutoReinstallOldVersionClient: 'WebConfig-OtherSettings',
	ConsentExpireSeconds: 'WebConfig-OtherSettings',
	CookieSameSiteMode: 'WebConfig-OtherSettings', // 20.3+
	CycleCapturesAfterSeconds: 'WebConfig-OtherSettings',
	DefaultAccessSessionInfoAttributes: 'WebConfig-OtherSettings',
	DefaultAccessSoundCaptureMode: 'WebConfig-OtherSettings',
	DefaultMeetingSoundCaptureMode: 'WebConfig-OtherSettings',
	DefaultScreenQualityLevel: 'WebConfig-OtherSettings',
	DefaultSupportSessionInfoAttributes: 'WebConfig-OtherSettings',
	DefaultSupportSoundCaptureMode: 'WebConfig-OtherSettings',
	DisableGuestFileTransfer: 'WebConfig-OtherSettings',
	DisableRemotePrinting: 'WebConfig-OtherSettings',
	DuoIntegrationKey: 'WebConfig-OtherSettings',
	DuoSecretKey: 'WebConfig-OtherSettings',
	DuoApiHostname: 'WebConfig-OtherSettings',
	GuestInfoRefreshSeconds: 'WebConfig-OtherSettings',
	GuestScreenshotMaxPixelCount: 'WebConfig-OtherSettings',
	GuestScreenshotMaxScalePercent: 'WebConfig-OtherSettings',
	HostClientDeviceFingerprintValidationLevel: 'WebConfig-OtherSettings',
	HostEligibleExpireSeconds: 'WebConfig-OtherSettings',
	HostSessionDisplayLimit: 'WebConfig-OtherSettings',
	InputIdleDisconnectTimeSeconds: 'WebConfig-OtherSettings',
	KeepAliveTimeSeconds: 'WebConfig-OtherSettings',
	MaxCommandResultCharacterCount: 'WebConfig-OtherSettings',
	MeetingSessionExpireSeconds: 'WebConfig-OtherSettings',
	RelayAddressableUri: 'WebConfig-OtherSettings',
	RunCommandKillAfterMilliseconds: 'WebConfig-OtherSettings',
	SessionTypeDisplayOrder: 'WebConfig-OtherSettings',
	ShouldRevalidateAccessToken: 'WebConfig-OtherSettings',
	SmtpEnableSsl: 'WebConfig-OtherSettings',
	SupportSessionExpireSeconds: 'WebConfig-OtherSettings',
	TicketReissueIntervalSeconds: 'WebConfig-OtherSettings',
	TrustDeviceExpireDays: 'WebConfig-OtherSettings',
	UsePersistentTicketCookie: 'WebConfig-OtherSettings',
	WebServerAddressableUri: 'WebConfig-OtherSettings',
};

const AppConfigDefaults = {
	SystemSettings: {
		AccessAutoConsentIfUserProcessNotRunning: 'false',
		AutoConsentIfUserProcessNotRunning: 'false',
		AutoConsentToBackstage: 'false',
		ClientServiceTimeoutMilliseconds: '15000',
		EmptySessionProgramsToStart: 'powershell.exe;cmd.exe;regedit.exe',
		IsBackstageDefault: 'false', // 19.3+
		IsUserAllowedToRequireConsent: 'false',
		MaxRetrySleepMilliseconds: '1800000',
		SupportAutoConsentIfUserProcessNotRunning: 'false'
	},
	UserInterfaceSettings: {
		AccessHideWallpaperOnConnect: 'true',
		AccessLockMachineOnConnect: 'false',
		AccessLockMachineOnDisconnect: 'false',
		AccessShowBalloonOnConnect: 'true',
		AccessShowBalloonOnHide: 'true',
		AccessShowSystemTrayIcon: 'true',
		AccessShowUnderControlBanner: 'true',
		AccessSuspendControlAtStartup: 'false',
		AlwaysOnTop: 'false',
		AlwaysDeleteSessionOnExit: 'false',
		AllowGuestInitiatedFileTransfer: 'true',
		AutoConsentAfterSeconds: '0',
		BeepOnConnect: 'false',
		CapturesDirectory: 'Captures',
		ColorTheme: 'DarkTheme', // 19.0+
		DisableClipboardCapture: 'false',
		FullScreenWhenMaximized: 'false',
		GuestAlwaysOnTop: 'false',
		HideWallpaperOnConnect: 'true',
		HostAlwaysOnTop: 'false',
		HelpProviderName: 'Google',
		IsMicrophoneMuted: 'false',
		ShowBalloonOnConnect: 'true',
		ShowFeedbackSurveyForm: 'true',
		ShowCloseDialogOnExit: 'true',
		ShowSystemTrayIcon: 'true',
		ShowTrayIconContextMenuStoreLoginCredentialsItem: 'false', // 20.5+
		SupportAccessHostFullScreenWhenMaximized: 'true',
		SupportHideWallpaperOnConnect: 'true',
		SupportLockMachineOnConnect: 'false',
		SupportLockMachineOnDisconnect: 'false',
		SupportShowBalloonOnConnect: 'true',
		SupportShowBalloonOnHide: 'true',
		SupportShowSystemTrayIcon: 'true',
		SupportShowUnderControlBanner: 'true',
		SupportSuspendControlAtStartup: 'false',
		ToolboxDirectory: 'Toolbox',
		FilesDirectory: 'Files',
		DisabledCommandNames: '',
		ControlPanelIDs: '0x0000001555111110',
		SupportAccessGuestControlPanelIDs: '0x0000001104000000',
		SupportAccessGuestRenderControlPanelIDs: '0x0000001115000000',
		SupportAccessGuestRenderDockControlPanelIDs: '0x0000000110000000',
		SupportAccessHostControlPanelIDs: '0x0000001555111100',
		CaptureControlPanelIDs: '0x0000001154000010',
		MeetingControlPanelIDs: '0x0000001155000000',
		SupportAccessDockControlPanelIDs: '0x0000000000000000',
		MeetingDockControlPanelIDs: '0x0000000110000000',
		MeetingSuspendControlAtStartup: 'false'
	},
	Bitmask: {
		Share: '0x0000000000000010',
		View: '0x0000000000000100',
		Essentials: '0x0000000000001000',
		Toolbox: '0x0000000000010000',
		FileTransfer: '0x0000000000100000',
		ScreenCapture: '0x0000000001000000',
		Sound: '0x0000000004000000',
		Annotations: '0x0000000040000000',
		Participants: '0x0000000010000000',
		Messages: '0x0000000100000000',
		Helper: '0x0000000400000000',
		Status: '0x0000001000000000'
	},
};

const WebConfigDefaults = {
	PageSettings: {
		AdminMaxLongestTicketReissueIntervalSeconds: '1800', // not in configpart
		BlockIPs: '',
		MaxLongestTicketReissueIntervalSeconds: '86400', // todo: why isn't this in ConfigPartition?
		MinAuthenticationFactorCount: '0',
		RestrictToIPs: '',
	},
	OtherSettings: {
		DisableRemotePrinting: 'false',
		AutoReinstallOldVersionClient: 'false',
		DefaultSupportSessionInfoAttributes: 'None',
		DefaultAccessSessionInfoAttributes: 'None',
		DefaultScreenQualityLevel: 'High',
		DefaultSupportSoundCaptureMode: 'Silent',
		DefaultAccessSoundCaptureMode: 'Silent',
		DefaultMeetingSoundCaptureMode: 'AllMicrophones',
		GuestScreenshotMaxPixelCount: '30000',
		GuestScreenshotMaxScalePercent: '20',
		HostSessionDisplayLimit: '1000',
		RunCommandKillAfterMilliseconds: '10000',
		AccessTokenExpireSeconds: '86400',
		SessionTypeDisplayOrder: 'Support,Meeting,Access',
		ShouldRevalidateAccessToken: 'false',
		InputIdleDisconnectTimeSeconds: '3600',
		SupportSessionExpireSeconds: '0',
		MeetingSessionExpireSeconds: '0',
		AccessSessionExpireSeconds: '0',
		SmtpEnableSsl: 'false',
		AllowPasswordAutoComplete: 'false',
		UsePersistentTicketCookie: 'true',
		CookieSameSiteMode: 'Lax', // 20.3+
		TicketReissueIntervalSeconds: '600',
		KeepAliveTimeSeconds: '60',
		ApplicationPingTimeSeconds: '1250',
		CycleCapturesAfterSeconds: '1800',
		MaxCommandResultCharacterCount: '5000',
		ConsentExpireSeconds: '3600',
		AcknowledgeMessageDelaySeconds: '600',
		HostEligibleExpireSeconds: '86400',
		GuestInfoRefreshSeconds: '1200',
		HostClientDeviceFingerprintValidationLevel: 'None',
		DuoIntegrationKey: '',
		DuoSecretKey: '',
		DuoApiHostname: '',
		TrustDeviceExpireDays: '30',
		RelayAddressableUri: '',
		WebServerAddressableUri: '',
	}
};